# Autumn theme for tmux-dotbar
set -g @tmux-dotbar-bg "#0F1b1f"
set -g @tmux-dotbar-fg "#243035"
set -g @tmux-dotbar-fg-current "#AF8D4B"
set -g @tmux-dotbar-fg-session "#e0e8ed"
set -g @tmux-dotbar-fg-prefix "#AF8D4B"
