# Catppuccin Mocha theme for tmux-dotbar
set -g @tmux-dotbar-bg "#1E1E2E"
set -g @tmux-dotbar-fg "#313244"
set -g @tmux-dotbar-fg-current "#b4befe"
set -g @tmux-dotbar-fg-session "#cdd6f4"
set -g @tmux-dotbar-fg-prefix "#b4befe"
