# Crimson theme for tmux-dotbar
set -g @tmux-dotbar-bg "#1C1C1C"
set -g @tmux-dotbar-fg "#3a1a1e"
set -g @tmux-dotbar-fg-current "#F5A78F"
set -g @tmux-dotbar-fg-session "#f8eeee"
set -g @tmux-dotbar-fg-prefix "#F5A78F"
