# Everforest theme for tmux-dotbar
set -g @tmux-dotbar-bg "#2D353B"
set -g @tmux-dotbar-fg "#3c474d"
set -g @tmux-dotbar-fg-current "#a7c080"
set -g @tmux-dotbar-fg-session "#d3c6aa"
set -g @tmux-dotbar-fg-prefix "#a7c080"
