# Graphite theme for tmux-dotbar
set -g @tmux-dotbar-bg "#1C1C1C"
set -g @tmux-dotbar-fg "#484848"
set -g @tmux-dotbar-fg-current "#ffffff"
set -g @tmux-dotbar-fg-session "#eeeeee"
set -g @tmux-dotbar-fg-prefix "#888888"
