# Gruvbox theme for tmux-dotbar
set -g @tmux-dotbar-bg "#282828"
set -g @tmux-dotbar-fg "#504945"
set -g @tmux-dotbar-fg-current "#b8bb26"
set -g @tmux-dotbar-fg-session "#fbf1c7"
set -g @tmux-dotbar-fg-prefix "#b8bb26"
