# Kanagawa theme for tmux-dotbar
set -g @tmux-dotbar-bg "#1F1F28"
set -g @tmux-dotbar-fg "#363646"
set -g @tmux-dotbar-fg-current "#7e9cd8"
set -g @tmux-dotbar-fg-session "#ecebe4"
set -g @tmux-dotbar-fg-prefix "#7e9cd8"
