# Night Owl theme for tmux-dotbar
set -g @tmux-dotbar-bg "#011627"
set -g @tmux-dotbar-fg "#1d3b53"
set -g @tmux-dotbar-fg-current "#82aaff"
set -g @tmux-dotbar-fg-session "#eef2f7"
set -g @tmux-dotbar-fg-prefix "#82aaff"
