# Oxocarbon theme for tmux-dotbar
set -g @tmux-dotbar-bg "#161616"
set -g @tmux-dotbar-fg "#393939"
set -g @tmux-dotbar-fg-current "#78a9ff"
set -g @tmux-dotbar-fg-session "#ffffff"
set -g @tmux-dotbar-fg-prefix "#78a9ff"
