# Rose Pine theme for tmux-dotbar
set -g @tmux-dotbar-bg "#232136"
set -g @tmux-dotbar-fg "#393552"
set -g @tmux-dotbar-fg-current "#c4a7e7"
set -g @tmux-dotbar-fg-session "#f0eef8"
set -g @tmux-dotbar-fg-prefix "#c4a7e7"
