exec-once = hyprpm reload -n
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = awww-daemon && sleep 0.5 && awww img $(readlink -f ~/.cache/wall-cache/current_wallpaper 2>/dev/null) --transition-type any --transition-duration 1 2>/dev/null || true
exec-once = swaync
exec-once = swayosd-server
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = nm-applet --no-indicator
exec-once = xhost +SI:localuser:root
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = playerctld

# Waybar
exec-once = waybar &
