#### List of plugins ####

# TPM
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Session management
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Utilities
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-open'

# Tmux Dotbar
set -g @plugin 'vaaleyard/tmux-dotbar'

# ---- Dotbar Options ---- #
set -g @tmux-dotbar-left "false"
set -g @tmux-dotbar-right "true"
set -g @tmux-dotbar-ssh-enabled true
set -g @tmux-dotbar-ssh-icon '󰌘'

# Source current theme colorscheme
source-file ~/.config/tmux/colorschemes/everforest.conf

# ---- Continuum Options ---- #
set -g @continuum-restore 'on'

# ---- Basic Tmux Settings ---- #
set-option -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

# Mouse support
set -g mouse on

# Faster escape time (for vim/neovim)
set -sg escape-time 0

# Larger scrollback buffer
set -g history-limit 50000

# Vi mode for copy
setw -g mode-keys vi



run '~/.config/tmux/plugins/tpm/tpm'
